/**
 * Core.Backend.Secure
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Timetable { 
    start?: string;
    end?: string;
    id?: number;
    classIds?: Array<number> | null;
    roomIds?: Array<number> | null;
    subjectIds?: Array<number> | null;
    teacherIds?: Array<number> | null;
    lessonType?: string | null;
    code?: string | null;
    substitutionText?: string | null;
}

